services:
  bleunova:
    build: .
    container_name: bleunova-ai-agent
    working_dir: /app
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/src

    ports:
      - "8000:8000"
      - "8501:8501"

    volumes:
      - ./:/app

    restart: unless-stopped
